trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo This pipeline is for VPC provisioning!
  displayName: 'VPC provision'

# Init backend
# apply

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/vpc'
    backendServiceAWS: 'aws-tf-service-connection'
    backendAWSBucketName: 'grpandurangi-s3-backend-terraform'
    backendAWSKey: 'grpandurangi-vpc'
  
# - task: TerraformTaskV1@0
#   inputs:
#     provider: 'aws'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/vpc'
#     environmentServiceNameAWS: 'aws-tf-service-connection'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/vpc'
    environmentServiceNameAWS: 'aws-tf-service-connection'



