trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo This pipeline is for K8S provision!!
  displayName: 'EKS K8S Provision'

# Init backend
# apply

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/kubernetes'
    backendServiceAWS: 'aws-tf-service-connection'
    backendAWSBucketName: 'grpandurangi-s3-backend-terraform'
    backendAWSKey: 'grpandurangi-eks'
  
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/kubernetes'
    commandOptions: '-var "vpc_id=$(VPC_ID)"'
    environmentServiceNameAWS: 'aws-tf-service-connection'

# - task: TerraformTaskV1@0
#   inputs:
#     provider: 'aws'
#     command: 'destroy'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/kubernetes'
#     commandOptions: '-var "vpc_id=$(VPC_ID)"'
#     environmentServiceNameAWS: 'aws-tf-service-connection'



