trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo This pipeline is for IAM for EC2 provisioning!
  displayName: 'IAM for EC2 Provision'

# Init backend
# apply

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/iam-role-ec2'
    backendServiceAWS: 'aws-tf-service-connection'
    backendAWSBucketName: 'grpandurangi-s3-backend-terraform'
    backendAWSKey: 'grpandurangi-iam-role-ec2'
  
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/iam-role-ec2'
    commandOptions: '-var "region=$(REGION)"'
    environmentServiceNameAWS: 'aws-tf-service-connection'

# - task: TerraformTaskV1@0
#   inputs:
#     provider: 'aws'
#     command: 'destroy'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/iam-role-ec2'
#     commandOptions: '-var "region=$(REGION)"'
#     environmentServiceNameAWS: 'aws-tf-service-connection'
    
